# MakeFile rpg_randomico

all: rpg_randomico

rpg_randomico: main.c funcoes.c menu/menu.c jogo/jogo.c jogador/jogador.c inimigo/inimigo.c rank/rank.c
	gcc -o rpg_randomico main.c funcoes.c menu/menu.c jogo/jogo.c jogador/jogador.c inimigo/inimigo.c rank/rank.c
